language: python
sudo: false
dist: trusty
python:
  - "2.7"
  - "3.5"

addons:
  apt:
    packages:
    - qemu

install:
  - pip install ansible librouteros pylint

script:
  # Lint
  - pylint library/*.py

  # Run Ansible integration test
  - ./test.sh
